src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $email = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $pseudo = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $create_at = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $update_at = null;

    /**
     * @var Collection<int, Trick>
     */
    #[ORM\OneToMany(targetEntity: Trick::class, mappedBy: 'user')]
    private Collection $trick;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'user')]
    private Collection $comment;

    #[ORM\Column]
    private bool $isVerified = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    public function __construct()
    {
        $this->trick = new ArrayCollection();
        $this->comment = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): static
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeInterface $update_at): static
    {
        $this->update_at = $update_at;

        return $this;
    }

    /**
     * @return Collection<int, Trick>
     */
    public function getTrick(): Collection
    {
        return $this->trick;
    }

    public function addTrick(Trick $trick): static
    {
        if (!$this->trick->contains($trick)) {
            $this->trick->add($trick);
            $trick->setUser($this);
        }

        return $this;
    }

    public function removeTrick(Trick $trick): static
    {
        if ($this->trick->removeElement($trick)) {
            // set the owning side to null (unless already changed)
            if ($trick->getUser() === $this) {
                $trick->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComment(): Collection
    {
        return $this->comment;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comment->contains($comment)) {
            $this->comment->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comment->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(?string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }
}

src/Form/TrickType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Trick;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;



class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'required' => true,
                'label' => 'Nom du trick',
            ])
            // ->add('image')
            ->add('image', TextType::class, [
                'required' => true,
                'label' => 'URL de l\'image',
                'constraints' => [
                    new Assert\NotBlank(['message' => 'L\'URL de l\'image est obligatoire.']),
                    new Assert\Url(['message' => 'Veuillez saisir une URL valide.']),
                ],
            ])
            ->add('slug', HiddenType::class, [
                'required' => false,
                'mapped' => false, // Désactiver le mapping si le slug est généré automatiquement
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description du trick',
                'required' => true,
                'attr' => ['rows' => 5],
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'label' => 'Catégorie',
                'placeholder' => 'Sélectionnez une catégorie',
            ])
            ->add('picture', CollectionType::class, [
                'entry_type' => PictureType::class, // Type du formulaire enfant
                'allow_add' => true, // Permet d'ajouter dynamiquement des images
                'allow_delete' => true, // Permet la suppression
                'by_reference' => false, // Important pour les relations OneToMany
                'prototype' => true, // Permet d'ajouter avec JavaScript
                'attr' => ['class' => 'picture-collection'],
            ])
            ->add('video', CollectionType::class, [
                'entry_type' => VideoType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'prototype' => true,
                'attr' => ['class' => 'video-collection'],
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Enregistrer le trick',
                'attr' => ['class' => 'btn btn-primary'],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Form\CommentType;
use App\Manager\CommentManagerInterface;
use App\Entity\Trick;
use App\Form\TrickType;
use App\Manager\TrickManagerInterface;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TrickController extends AbstractController
{
    private TrickManagerInterface $trickManager;
    private CommentManagerInterface $commentManager;

    public function __construct(TrickManagerInterface $trickManager, CommentManagerInterface $commentManager)
    {
        $this->trickManager = $trickManager;
        $this->commentManager = $commentManager;
    }

    //Créer un trick
    #[Route('/trick/new', name: 'app_trick_new')]
    public function new(Request $request): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $this->denyAccessUnlessGranted('ROLE_USER');

        $trick = new Trick();
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $trick->setUser($this->getUser());

            if ($this->trickManager->createTrick($trick)) {
                $this->addFlash('success', 'Trick créé avec succès !');

                return $this->redirectToRoute('app_trick_show', [
                    'slug' => $trick->getSlug(),
                ]);
            } else {
                $this->addFlash('error', 'Le slug existe déjà, veuillez modifier le nom.');
            }
        }

        return $this->render('trick/form.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/trick/{slug}', name: 'app_trick_show')]
    public function show(Request $request, string $slug): Response
    {
        $trick = $this->trickManager->getTrick($slug);

        if (!$trick) {
            throw $this->createNotFoundException('Trick non trouvé');
        }

        $comments = $this->commentManager->getCommentsByTrick($trick);

        $comment = $this->commentManager->createCommentForTrick($trick);
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->commentManager->handleNewComment($comment, $this->getUser());
            $this->addFlash('success', 'Commentaire ajouté');

            return $this->redirectToRoute('app_trick_show', ['slug' => $trick->getSlug()]);
        }

        return $this->render('trick/index.html.twig', [
            'trick' => $trick,
            'comments' => $comments,
            'form' => $form,
        ]);
    }

    //supprimer un trick
    #[Route('/trick/{slug}/delete', name: 'app_trick_remove')]
    public function remove(string $slug): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $trick = $this->trickManager->getTrick($slug);

        $isdelete = $this->trickManager->deleteTrick($trick);

        if (!$isdelete) {
            $this->addFlash('success', 'Suppression effectuée');
        } else {
            $this->addFlash('error', 'Échec de la suppression');
        }

        return $this->redirectToRoute('app_home');
    }

    #[Route('/trick/{slug}/edit', name: 'app_trick_edit')]
    public function edit(Request $request, string $slug, EntityManagerInterface $entityManager): Response
    {
        // Recherche du trick par son slug
        $trick = $this->trickManager->getTrick($slug);
        $form = $this->createForm(TrickType::class, $trick);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                try {
                    $trick->setUser($this->getUser());
                    $this->trickManager->updateTrick($trick);

                    $this->addFlash('success', 'Le trick a été modifié avec succès.');
                    return $this->redirectToRoute('app_trick_show', [
                        'slug' => $trick->getSlug(),
                    ]);
                } catch (UniqueConstraintViolationException $e) {
                    $this->addFlash('error', 'Ce nom de trick est déjà utilisé. Veuillez en choisir un autre.');
                }
            } else {
                $this->addFlash('error', 'Il y a une erreur dans le formulaire.');
            }
        }

        return $this->render('trick/edit.html.twig', [
            'trick' => $trick,
            'form' => $form,
        ]);
    }
}

templates/trick/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un Trick
{% endblock %}
{% block hero %}
	<div class="hero-picture img-shadow">
		<img src="{{ trick.image }}" alt="Image présentant la figure {{ trick.name }}" class="img-shadow">
		<div class="hero-text grand-text ombre">
			<h1>{{trick.name}}</h1>
		</div>
	</div>
{% endblock %}
{% block zoneOne %}
	<div class="contain">
		<div>
			<div class="form-error">
				{{ form_errors(form, {'attr': {'class': 'error-message'}}) }}
			</div>
			{{ form_start(form , {'method': 'POST'}) }}
			<div class="flex-column gap10">
				<h3>Images de mise en avant</h3>
				<div id="editTrick-input" class="flex-column">
					{{ form_row(form.image, {'attr': {'class': 'form-control'}}) }}
					{{ form_errors(form.image, {'attr': {'class': 'error-message'}}) }}
				</div>
				<div class="mb-1">
					{{ form_label(form.name) }}
					{{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
					{{ form_errors(form.name, {'attr': {'class': 'error-message'}}) }}
				</div>
			</div>
			<div id="zone-media">
				<div class="zone-media">
					<h3>Images associées</h3>
					<button type="button" class="btn btn-success mt-2" id="add-picture">Ajouter une image</button>
					<div id="picture-collection" data-prototype="{{ form_widget(form.picture.vars.prototype)|e('html_attr') }}">
						{% for picture in form.picture %}
							<div class="picture-item d-flex align-items-start mb-3 carte-collection">
								{% if picture.vars.value.src is not empty %}
									<img src="{{ picture.vars.value.src }}" alt="Image du Trick" class="img-thumbnail mb-2">
								{% endif %}
								<div class="flex-column zone-media-form">
									{{ form_row(picture.name, {'attr': {'class': 'form-control me-2'}}) }}
									{{ form_row(picture.src, {'attr': {'class': 'form-control me-2'}}) }}
									<button type="button" class="btn btn-danger remove-picture">Supprimer</button>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
				<div class="zone-media">
					<h3>Vidéos associées</h3>
					<button type="button" class="btn btn-success mt-2" id="add-video">Ajouter une vidéo</button>
					<div id="video-collection" data-prototype="{{ form_widget(form.video.vars.prototype)|e('html_attr') }}">
						{% for video in form.video %}
							<div class="video-item d-flex align-items-start mb-3 carte-collection">
								{% if video.vars.value.src is not empty %}
									<div class="flex-column zone-media-iframe">
										<iframe src="{{ video.vars.value.src | replace({'youtu.be/': 'www.youtube.com/embed/', 'watch?v=': 'embed/'}) }}" frameborder="0" allowfullscreen class="mb-2"></iframe>
									</div>
								{% endif %}
								<div class="flex-column zone-media-form">
									{{ form_row(video.name, {'attr': {'class': 'form-control me-2'}}) }}
									{{ form_row(video.src, {'attr': {'class': 'form-control me-2'}}) }}
									<button type="button" class="btn btn-danger remove-video">Supprimer</button>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>

			</div>
			<div class="mb-3">
				{{ form_label(form.description) }}
				{{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
				{{ form_errors(form.description, {'attr': {'class': 'error-message'}}) }}
			</div>

			<div class="mb-1">
				{{ form_label(form.category) }}
				{{ form_widget(form.category, {'attr': {'class': 'form-select'}}) }}
				{{ form_errors(form.category, {'attr': {'class': 'error-message'}}) }}
			</div>
			{% if form.picture.vars.data is empty %}
				<div class="hidden">
					{{ form_widget(form.picture) }}
				</div>
			{% endif %}

			{% if form.video.vars.data is empty %}
				<div class="hidden">
					{{ form_widget(form.video) }}
				</div>
			{% endif %}


			{{form_row(form.submit)}}
			{{ form_end(form) }}
		</div>
	</div>
{% endblock %}

templates/trick/form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer un trick
{% endblock %}
{% block hero %}
	<div class="hero-picture ">
		<img src="" alt="">
		<div class="hero-text grand-text ombre">
			<h1></h1>
		</div>
	</div>
{% endblock %}
{% block zoneOne %}
	<div class="contain">
		<div>
			<div class="form-error">
				{{ form_errors(form) }}
			</div>
			{{ form_start(form , {'method': 'POST'}) }}
			<div class="flex-column gap10">
				<h3>Images de mise en avant</h3>
				<div id="editTrick-input" class="flex-column">
					{{ form_row(form.image, {'attr': {'class': 'form-control'}}) }}
					{{ form_errors(form.image) }}
				</div>
				<div class="mb-1">
					{{ form_label(form.name) }}
					{{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
					{{ form_errors(form.name) }}
				</div>
			</div>
			<div id="zone-media">
				<div class="zone-media">
					<h3>Images associées</h3>
					<button type="button" class="btn btn-success mt-2" id="add-picture">Ajouter une image</button>
					<div id="picture-collection" data-prototype="{{ form_widget(form.picture.vars.prototype)|e('html_attr') }}">
						{% for picture in form.picture %}
							<div class="picture-item d-flex align-items-start mb-3 carte-collection">
								{% if picture.vars.value.src is not empty %}
									<img src="{{ picture.vars.value.src }}" alt="Image du Trick" class="img-thumbnail mb-2" style="width: 210px; height : 210px ">
								{% endif %}
								<div class="flex-column zone-media-form">
									{{ form_row(picture.name, {'attr': {'class': 'form-control me-2'}}) }}
									{{ form_row(picture.src, {'attr': {'class': 'form-control me-2'}}) }}
									<button type="button" class="btn btn-danger remove-picture">Supprimer</button>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>

				<div class="zone-media">
					<h3>Vidéos associées</h3>
					<button type="button" class="btn btn-success mt-2" id="add-video">Ajouter une vidéo</button>
					<div id="video-collection" data-prototype="{{ form_widget(form.video.vars.prototype)|e('html_attr') }}">
						{% for video in form.video %}
							<div class="video-item d-flex align-items-start mb-3 carte-collection">
								{% if video.vars.value.src is not empty %}
									<div class="flex-column zone-media-iframe">
										<iframe src="{{ video.vars.value.src | replace({'youtu.be/': 'www.youtube.com/embed/', 'watch?v=': 'embed/'}) }}" frameborder="0" allowfullscreen class="mb-2"></iframe>
									</div>
								{% endif %}
								<div class="flex-column zone-media-form">
									{{ form_row(video.name, {'attr': {'class': 'form-control me-2'}}) }}
									{{ form_row(video.src, {'attr': {'class': 'form-control me-2'}}) }}
									<button type="button" class="btn btn-danger remove-video">Supprimer</button>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>

			</div>


			<div class="mb-3">
				{{ form_label(form.description) }}
				{{ form_widget(form.description, {'attr': {'class': 'form-control'}}) }}
				{{ form_errors(form.description) }}
			</div>

			<div class="mb-1">
				{{ form_label(form.category) }}
				{{ form_widget(form.category, {'attr': {'class': 'form-select'}}) }}
				{{ form_errors(form.category) }}
			</div>

			<div class="hidden">
				{{ form_widget(form.picture) }}
				{{ form_widget(form.video) }}
			</div>
			{{form_row(form.submit)}}
			{{ form_end(form) }}
		</div>
	</div>
{% endblock %}

templates/trick/index.html.twig
{% extends 'base.html.twig' %}
{% block title %}SnowTricks - trick
{% endblock %}

{% block hero %}
	<div class="hero-picture">
		<img src="{{ trick.image }}" alt="Image présentant la figure {{ trick.name }}" class="img-shadow">
		<div class="hero-text text-shadow">
			<h1>{{trick.name}}</h1>
		</div>

		{% if app.user %}
			<div id="btn-trickZone" class="flex">
				<a href="{{ path('app_trick_edit',{slug : trick.slug}) }}">
					<button type="button" class="btn btn-primary mt-2">
						<i class="fa-solid fa-pen"></i>
					</button>
				</a>
				<a href="{{ path('app_trick_remove',{slug : trick.slug}) }}" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce trick ? Cette action est irréversible.')">
					<button type="submit" class="btn btn-primary mt-2">
						<i class="fa-solid fa-trash"></i>
					</button>
				</a>
			</div>
		{% endif %}
	</div>
{% endblock %}

{% block zoneOne %}
	<div class="contain">
		{% if trick.picture is not empty or trick.video is not empty %}
			<div id="media">
				{% for picture in trick.picture %}
					<a href="#" class="col-sm-3" data-bs-toggle="modal" data-bs-target="#lightboxModal">
						<div class="figure">
							<img data-bs-target="#lightboxCarousel" data-bs-slide-to="{{ loop.index0 }}" src="{{ picture.src }}" class="figure-img img-fluid rounded">
						</div>
					</a>
				{% endfor %}
				{% for video in trick.video %}
					{% if "youtube.com" in video.src or "youtu.be" in video.src %}
						<iframe src="{{ video.src | replace({'youtu.be/': 'www.youtube.com/embed/', 'watch?v=': 'embed/'}) }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
					{% else %}
						<video controls width="250">
							<source src="{{ video.src }}" type="video/mp4">
							<a href="{{ video.src }}">MP4</a>
						</video>
					{% endif %}
				{% endfor %}
			</div>
			<hr class="my-4"/>
		{% endif %}
		<div class="modal fade" id="lightboxModal" tabindex="-1" aria-labelledby="lightboxModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-xl modal-dialog-centered">
				<div class="modal-content">
					<div class="modal-body">
						<div id="lightboxCarousel" class="carousel slide" data-bs-ride="carousel">
							<div class="carousel-inner ratio ratio-16x9 bg-dark">
								{% for picture in trick.picture %}
									<div class="carousel-item {% if loop.first %}active{% endif %} text-center">
										<img src="{{ picture.src }}" class="img-fluid mh-100">
									</div>
								{% endfor %}
								{% for video in trick.video %}
									<div class="carousel-item text-center">
										{% if "youtube.com" in video.src or "youtu.be" in video.src %}
											<iframe class="img-fluid mh-200" src="{{ video.src | replace({'youtu.be/': 'www.youtube.com/embed/', 'watch?v=': 'embed/'}) }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
										{% else %}
											<video controls class="img-fluid mh-100">
												<source src="{{ video.src }}" type="video/mp4">
												<a href="{{ video.src }}">MP4</a>
											</video>
										{% endif %}
									</div>
								{% endfor %}
							</div>
							<button class="carousel-control-prev" type="button" data-bs-target="#lightboxCarousel" data-bs-slide="prev">
								<span class="carousel-control-prev-icon" aria-hidden="true"></span>
								<span class="visually-hidden">Previous</span>
							</button>
							<button class="carousel-control-next" type="button" data-bs-target="#lightboxCarousel" data-bs-slide="next">
								<span class="carousel-control-next-icon" aria-hidden="true"></span>
								<span class="visually-hidden">Next</span>
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="btn-resp-display">
			<button class="btn btn-primary mt-2" type="button" onclick="toggleMedia()">Voir les médias</button>
		</div>
		<div id="details" class="flex-column-center">
			<h2>{{trick.name}}</h2>
			<div id="details-descr">{{trick.description}}</div>
			<div id="details-info" class="flex">
				<p class="encart">{{ trick.category.name }}</p>
				<p class="encart">
					Mise en ligne :
					{{trick.createAt|date("d/m/Y")}}</p>
				<p class="encart">Dernière modification :
					{{trick.updateAt|date("d/m/Y")}}</p>
			</div>
		</div>
		<hr class="my-4"/>
		<div id="details-info" class="flex-column">
			{% if app.user %}
				<div id="comment-form" class="mt-4">
					<div class="">
						<div class="card-body">
							{{ form_start(form, {'attr': {'class': 'needs-validation'}}) }}
							<div class="form-group">
								{{ form_label(form.content, 'Ajouter un commentaire', {'label_attr': {'for': 'commentContent', 'class': 'form-label'}}) }}
								{{ form_widget(form.content, {'attr': {'class': 'form-control', 'id': 'commentContent', 'rows': 4}}) }}
								{{ form_errors(form.content) }}
							</div>
							<div class="flex-center">
								<button type="submit" class="btn btn-primary mt-2">Envoyer</button>
							</div>
							{{ form_end(form) }}
						</div>
					</div>
				</div>
				<hr class="my-4"/>
			{% endif %}
		</div>
		<div id="comments-container">
			{% for comment in trick.comments %}
				<div class="comment-bloc flex-column" {% if loop.index > 5 %} style="display: none;" {% else %} style="display: flex;" {% endif %}>
					<div class="commentaire flex">
						<div class="avatar">
							{% if comment.user and comment.user.avatar %}
								<img src="{{ comment.user.avatar }}" alt="Avatar de {{ comment.user.pseudo }}" class="avatar-img">
							{% else %}
								<img src="https://img.freepik.com/free-vector/para-snowboard-concept-illustration_114360-18502.jpg?t=st=1739357466~exp=1739361066~hmac=b818099bdbc92853d7d27ba02bc77f9772328ee776b0a503dbdb1f312a5d7408&w=740" alt="Avatar par défaut" class="avatar-img">
							{% endif %}
						</div>
						<div class="texte">
							<div class="tl700">{{ comment.user.pseudo }}</div>
							<div class="txtI200">{{ comment.createAt|date("d/m/Y")}}</div>
							<div class="topgap10">{{ comment.content }}</div>
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
		{% if trick.comments|length > 5 %}
			<div class="flex-center">
				<button id="load-more" class="btn btn-primary mt-2">Afficher plus</button>
			</div>
		{% endif %}

	</div>
	<script>
		function toggleMedia() {
var mediaDiv = document.getElementById('media');
var button = document.querySelector('#btn-resp-display button');

// Toggle the display of the media div
if (mediaDiv.style.display === 'none' || mediaDiv.style.display === '') {
mediaDiv.style.display = 'block';
button.textContent = "Masquer les médias"; // Change button text when media is shown
} else {
mediaDiv.style.display = 'none';
button.textContent = "Voir les médias"; // Revert button text when media is hidden
}
}
	</script>
{% endblock %}